[workspace]
members = ["programs/*", "encrypted-ixs"]
resolver = "2"

[profile.release]
overflow-checks = true

[patch.crates-io]
anchor-syn = { path = "./vendor/anchor-syn-0.32.1" }
base64ct = { path = "./patches/base64ct" }
const-oid = { path = "./patches/const-oid" }
